# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: game/model.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

import betterproto
from pydantic.dataclasses import rebuild_dataclass

from .. import root_models as _root_models__


@dataclass(eq=False, repr=False)
class ShipGridView(betterproto.Message):
    hit_grid: "list[ShipGridViewRow]" = betterproto.message_field(1)
    ships: "list[ActiveShip]" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ShipGridViewRow(betterproto.Message):
    cells: "list[bool]" = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class ActiveShip(betterproto.Message):
    length: int = betterproto.int32_field(1)
    orientation: "_root_models__.Orientation" = betterproto.enum_field(2)
    head_row: int = betterproto.int32_field(3)
    head_col: int = betterproto.int32_field(4)
    hits: "list[bool]" = betterproto.bool_field(5)


rebuild_dataclass(ShipGridView)  # type: ignore
rebuild_dataclass(ActiveShip)  # type: ignore
