/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Orientation } from './Orientation';
import {
    OrientationFromJSON,
    OrientationFromJSONTyped,
    OrientationToJSON,
    OrientationToJSONTyped,
} from './Orientation';

/**
 * 
 * @export
 * @interface ActiveShip
 */
export interface ActiveShip {
    /**
     * 
     * @type {number}
     * @memberof ActiveShip
     */
    length: number;
    /**
     * 
     * @type {Orientation}
     * @memberof ActiveShip
     */
    orientation: Orientation;
    /**
     * 
     * @type {number}
     * @memberof ActiveShip
     */
    headRow: number;
    /**
     * 
     * @type {number}
     * @memberof ActiveShip
     */
    headCol: number;
    /**
     * 
     * @type {number}
     * @memberof ActiveShip
     */
    hits?: number;
}



/**
 * Check if a given object implements the ActiveShip interface.
 */
export function instanceOfActiveShip(value: object): value is ActiveShip {
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('orientation' in value) || value['orientation'] === undefined) return false;
    if (!('headRow' in value) || value['headRow'] === undefined) return false;
    if (!('headCol' in value) || value['headCol'] === undefined) return false;
    return true;
}

export function ActiveShipFromJSON(json: any): ActiveShip {
    return ActiveShipFromJSONTyped(json, false);
}

export function ActiveShipFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveShip {
    if (json == null) {
        return json;
    }
    return {
        
        'length': json['length'],
        'orientation': OrientationFromJSON(json['orientation']),
        'headRow': json['headRow'],
        'headCol': json['headCol'],
        'hits': json['hits'] == null ? undefined : json['hits'],
    };
}

export function ActiveShipToJSON(json: any): ActiveShip {
    return ActiveShipToJSONTyped(json, false);
}

export function ActiveShipToJSONTyped(value?: ActiveShip | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'length': value['length'],
        'orientation': OrientationToJSON(value['orientation']),
        'headRow': value['headRow'],
        'headCol': value['headCol'],
        'hits': value['hits'],
    };
}

