/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { View } from './View';
import {
    ViewFromJSON,
    ViewFromJSONTyped,
    ViewToJSON,
    ViewToJSONTyped,
} from './View';

/**
 * 
 * @export
 * @interface GameWSServerStateMessage
 */
export interface GameWSServerStateMessage {
    /**
     * 
     * @type {View}
     * @memberof GameWSServerStateMessage
     */
    ownShipGrid: View;
    /**
     * 
     * @type {View}
     * @memberof GameWSServerStateMessage
     */
    opponentShipGrid: View;
}

/**
 * Check if a given object implements the GameWSServerStateMessage interface.
 */
export function instanceOfGameWSServerStateMessage(value: object): value is GameWSServerStateMessage {
    if (!('ownShipGrid' in value) || value['ownShipGrid'] === undefined) return false;
    if (!('opponentShipGrid' in value) || value['opponentShipGrid'] === undefined) return false;
    return true;
}

export function GameWSServerStateMessageFromJSON(json: any): GameWSServerStateMessage {
    return GameWSServerStateMessageFromJSONTyped(json, false);
}

export function GameWSServerStateMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameWSServerStateMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'ownShipGrid': ViewFromJSON(json['ownShipGrid']),
        'opponentShipGrid': ViewFromJSON(json['opponentShipGrid']),
    };
}

export function GameWSServerStateMessageToJSON(json: any): GameWSServerStateMessage {
    return GameWSServerStateMessageToJSONTyped(json, false);
}

export function GameWSServerStateMessageToJSONTyped(value?: GameWSServerStateMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ownShipGrid': ViewToJSON(value['ownShipGrid']),
        'opponentShipGrid': ViewToJSON(value['opponentShipGrid']),
    };
}

