/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameParams
 */
export interface GameParams {
    /**
     * 
     * @type {number}
     * @memberof GameParams
     */
    battleGridRows: number;
    /**
     * 
     * @type {number}
     * @memberof GameParams
     */
    battleGridCols: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof GameParams
     */
    shipLengths: Array<number>;
}

/**
 * Check if a given object implements the GameParams interface.
 */
export function instanceOfGameParams(value: object): value is GameParams {
    if (!('battleGridRows' in value) || value['battleGridRows'] === undefined) return false;
    if (!('battleGridCols' in value) || value['battleGridCols'] === undefined) return false;
    if (!('shipLengths' in value) || value['shipLengths'] === undefined) return false;
    return true;
}

export function GameParamsFromJSON(json: any): GameParams {
    return GameParamsFromJSONTyped(json, false);
}

export function GameParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameParams {
    if (json == null) {
        return json;
    }
    return {
        
        'battleGridRows': json['battle_grid_rows'],
        'battleGridCols': json['battle_grid_cols'],
        'shipLengths': json['ship_lengths'],
    };
}

export function GameParamsToJSON(json: any): GameParams {
    return GameParamsToJSONTyped(json, false);
}

export function GameParamsToJSONTyped(value?: GameParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'battle_grid_rows': value['battleGridRows'],
        'battle_grid_cols': value['battleGridCols'],
        'ship_lengths': value['shipLengths'],
    };
}

