/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameWSPlayerShotMessage
 */
export interface GameWSPlayerShotMessage {
    /**
     * 
     * @type {number}
     * @memberof GameWSPlayerShotMessage
     */
    row: number;
    /**
     * 
     * @type {number}
     * @memberof GameWSPlayerShotMessage
     */
    col: number;
}

/**
 * Check if a given object implements the GameWSPlayerShotMessage interface.
 */
export function instanceOfGameWSPlayerShotMessage(value: object): value is GameWSPlayerShotMessage {
    if (!('row' in value) || value['row'] === undefined) return false;
    if (!('col' in value) || value['col'] === undefined) return false;
    return true;
}

export function GameWSPlayerShotMessageFromJSON(json: any): GameWSPlayerShotMessage {
    return GameWSPlayerShotMessageFromJSONTyped(json, false);
}

export function GameWSPlayerShotMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameWSPlayerShotMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'row': json['row'],
        'col': json['col'],
    };
}

export function GameWSPlayerShotMessageToJSON(json: any): GameWSPlayerShotMessage {
    return GameWSPlayerShotMessageToJSONTyped(json, false);
}

export function GameWSPlayerShotMessageToJSONTyped(value?: GameWSPlayerShotMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row': value['row'],
        'col': value['col'],
    };
}

