/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PregameParams
 */
export interface PregameParams {
    /**
     * 
     * @type {number}
     * @memberof PregameParams
     */
    battleGridRows: number;
    /**
     * 
     * @type {number}
     * @memberof PregameParams
     */
    battleGridCols: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof PregameParams
     */
    shipLengths: Array<number>;
}

/**
 * Check if a given object implements the PregameParams interface.
 */
export function instanceOfPregameParams(value: object): value is PregameParams {
    if (!('battleGridRows' in value) || value['battleGridRows'] === undefined) return false;
    if (!('battleGridCols' in value) || value['battleGridCols'] === undefined) return false;
    if (!('shipLengths' in value) || value['shipLengths'] === undefined) return false;
    return true;
}

export function PregameParamsFromJSON(json: any): PregameParams {
    return PregameParamsFromJSONTyped(json, false);
}

export function PregameParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PregameParams {
    if (json == null) {
        return json;
    }
    return {
        
        'battleGridRows': json['battle_grid_rows'],
        'battleGridCols': json['battle_grid_cols'],
        'shipLengths': json['ship_lengths'],
    };
}

export function PregameParamsToJSON(json: any): PregameParams {
    return PregameParamsToJSONTyped(json, false);
}

export function PregameParamsToJSONTyped(value?: PregameParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'battle_grid_rows': value['battleGridRows'],
        'battle_grid_cols': value['battleGridCols'],
        'ship_lengths': value['shipLengths'],
    };
}

