/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ship } from './Ship';
import {
    ShipFromJSON,
    ShipFromJSONTyped,
    ShipToJSON,
    ShipToJSONTyped,
} from './Ship';

/**
 * 
 * @export
 * @interface PregameWSPlayerReadyMessage
 */
export interface PregameWSPlayerReadyMessage {
    /**
     * 
     * @type {Array<Ship>}
     * @memberof PregameWSPlayerReadyMessage
     */
    ships: Array<Ship>;
}

/**
 * Check if a given object implements the PregameWSPlayerReadyMessage interface.
 */
export function instanceOfPregameWSPlayerReadyMessage(value: object): value is PregameWSPlayerReadyMessage {
    if (!('ships' in value) || value['ships'] === undefined) return false;
    return true;
}

export function PregameWSPlayerReadyMessageFromJSON(json: any): PregameWSPlayerReadyMessage {
    return PregameWSPlayerReadyMessageFromJSONTyped(json, false);
}

export function PregameWSPlayerReadyMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PregameWSPlayerReadyMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'ships': ((json['ships'] as Array<any>).map(ShipFromJSON)),
    };
}

export function PregameWSPlayerReadyMessageToJSON(json: any): PregameWSPlayerReadyMessage {
    return PregameWSPlayerReadyMessageToJSONTyped(json, false);
}

export function PregameWSPlayerReadyMessageToJSONTyped(value?: PregameWSPlayerReadyMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ships': ((value['ships'] as Array<any>).map(ShipToJSON)),
    };
}

