/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PregameWSServerStateMessage
 */
export interface PregameWSServerStateMessage {
    /**
     * 
     * @type {number}
     * @memberof PregameWSServerStateMessage
     */
    numPlayersReady: number;
    /**
     * 
     * @type {boolean}
     * @memberof PregameWSServerStateMessage
     */
    selfReady: boolean;
}

/**
 * Check if a given object implements the PregameWSServerStateMessage interface.
 */
export function instanceOfPregameWSServerStateMessage(value: object): value is PregameWSServerStateMessage {
    if (!('numPlayersReady' in value) || value['numPlayersReady'] === undefined) return false;
    if (!('selfReady' in value) || value['selfReady'] === undefined) return false;
    return true;
}

export function PregameWSServerStateMessageFromJSON(json: any): PregameWSServerStateMessage {
    return PregameWSServerStateMessageFromJSONTyped(json, false);
}

export function PregameWSServerStateMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PregameWSServerStateMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'numPlayersReady': json['num_players_ready'],
        'selfReady': json['self_ready'],
    };
}

export function PregameWSServerStateMessageToJSON(json: any): PregameWSServerStateMessage {
    return PregameWSServerStateMessageToJSONTyped(json, false);
}

export function PregameWSServerStateMessageToJSONTyped(value?: PregameWSServerStateMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'num_players_ready': value['numPlayersReady'],
        'self_ready': value['selfReady'],
    };
}

