/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActiveShip } from './ActiveShip';
import {
    ActiveShipFromJSON,
    ActiveShipFromJSONTyped,
    ActiveShipToJSON,
    ActiveShipToJSONTyped,
} from './ActiveShip';

/**
 * 
 * @export
 * @interface View
 */
export interface View {
    /**
     * 
     * @type {Array<Array<boolean>>}
     * @memberof View
     */
    cells: Array<Array<boolean>>;
    /**
     * 
     * @type {Array<ActiveShip>}
     * @memberof View
     */
    ships: Array<ActiveShip>;
}

/**
 * Check if a given object implements the View interface.
 */
export function instanceOfView(value: object): value is View {
    if (!('cells' in value) || value['cells'] === undefined) return false;
    if (!('ships' in value) || value['ships'] === undefined) return false;
    return true;
}

export function ViewFromJSON(json: any): View {
    return ViewFromJSONTyped(json, false);
}

export function ViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): View {
    if (json == null) {
        return json;
    }
    return {
        
        'cells': json['cells'],
        'ships': ((json['ships'] as Array<any>).map(ActiveShipFromJSON)),
    };
}

export function ViewToJSON(json: any): View {
    return ViewToJSONTyped(json, false);
}

export function ViewToJSONTyped(value?: View | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cells': value['cells'],
        'ships': ((value['ships'] as Array<any>).map(ActiveShipToJSON)),
    };
}

