// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file root/messages.proto (package root_messages, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PregamePlayerMessage, PregameServerMessage } from "../pregame/messages_pb";
import { file_pregame_messages } from "../pregame/messages_pb";
import type { GamePlayerMessage, GameServerMessage } from "../game/messages_pb";
import { file_game_messages } from "../game/messages_pb";
import type { GeneralPlayerMessage, GeneralServerMessage } from "../general/messages_pb";
import { file_general_messages } from "../general/messages_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file root/messages.proto.
 */
export const file_root_messages: GenFile = /*@__PURE__*/
  fileDesc("ChNyb290L21lc3NhZ2VzLnByb3RvEg1yb290X21lc3NhZ2VzIu0BCg1QbGF5ZXJNZXNzYWdlEhEKCXRpbWVzdGFtcBgBIAEoBBJBCg9wcmVnYW1lX21lc3NhZ2UYAiABKAsyJi5wcmVnYW1lX21lc3NhZ2VzLlByZWdhbWVQbGF5ZXJNZXNzYWdlSAASOAoMZ2FtZV9tZXNzYWdlGAMgASgLMiAuZ2FtZV9tZXNzYWdlcy5HYW1lUGxheWVyTWVzc2FnZUgAEkEKD2dlbmVyYWxfbWVzc2FnZRgEIAEoCzImLmdlbmVyYWxfbWVzc2FnZXMuR2VuZXJhbFBsYXllck1lc3NhZ2VIAEIJCgdwYXlsb2FkIu0BCg1TZXJ2ZXJNZXNzYWdlEhEKCXRpbWVzdGFtcBgBIAEoBBJBCg9nZW5lcmFsX21lc3NhZ2UYAiABKAsyJi5nZW5lcmFsX21lc3NhZ2VzLkdlbmVyYWxTZXJ2ZXJNZXNzYWdlSAASQQoPcHJlZ2FtZV9tZXNzYWdlGAMgASgLMiYucHJlZ2FtZV9tZXNzYWdlcy5QcmVnYW1lU2VydmVyTWVzc2FnZUgAEjgKDGdhbWVfbWVzc2FnZRgEIAEoCzIgLmdhbWVfbWVzc2FnZXMuR2FtZVNlcnZlck1lc3NhZ2VIAEIJCgdwYXlsb2FkQnIKEWNvbS5yb290X21lc3NhZ2VzQg1NZXNzYWdlc1Byb3RvUAGiAgNSWFiqAgxSb290TWVzc2FnZXPKAgxSb290TWVzc2FnZXPiAhhSb290TWVzc2FnZXNcR1BCTWV0YWRhdGHqAgxSb290TWVzc2FnZXNiBnByb3RvMw", [file_pregame_messages, file_game_messages, file_general_messages]);

/**
 * @generated from message root_messages.PlayerMessage
 */
export type PlayerMessage = Message<"root_messages.PlayerMessage"> & {
  /**
   * @generated from field: uint64 timestamp = 1;
   */
  timestamp: bigint;

  /**
   * @generated from oneof root_messages.PlayerMessage.payload
   */
  payload: {
    /**
     * @generated from field: pregame_messages.PregamePlayerMessage pregame_message = 2;
     */
    value: PregamePlayerMessage;
    case: "pregameMessage";
  } | {
    /**
     * @generated from field: game_messages.GamePlayerMessage game_message = 3;
     */
    value: GamePlayerMessage;
    case: "gameMessage";
  } | {
    /**
     * @generated from field: general_messages.GeneralPlayerMessage general_message = 4;
     */
    value: GeneralPlayerMessage;
    case: "generalMessage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message root_messages.PlayerMessage.
 * Use `create(PlayerMessageSchema)` to create a new message.
 */
export const PlayerMessageSchema: GenMessage<PlayerMessage> = /*@__PURE__*/
  messageDesc(file_root_messages, 0);

/**
 * @generated from message root_messages.ServerMessage
 */
export type ServerMessage = Message<"root_messages.ServerMessage"> & {
  /**
   * @generated from field: uint64 timestamp = 1;
   */
  timestamp: bigint;

  /**
   * @generated from oneof root_messages.ServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: general_messages.GeneralServerMessage general_message = 2;
     */
    value: GeneralServerMessage;
    case: "generalMessage";
  } | {
    /**
     * @generated from field: pregame_messages.PregameServerMessage pregame_message = 3;
     */
    value: PregameServerMessage;
    case: "pregameMessage";
  } | {
    /**
     * @generated from field: game_messages.GameServerMessage game_message = 4;
     */
    value: GameServerMessage;
    case: "gameMessage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message root_messages.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema: GenMessage<ServerMessage> = /*@__PURE__*/
  messageDesc(file_root_messages, 1);

