// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file root/messages.proto (package root_messages, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PregamePlayerMessage, PregameServerMessage } from "../pregame/messages_pb";
import { file_pregame_messages } from "../pregame/messages_pb";
import type { GamePlayerMessage, GameServerMessage } from "../game/messages_pb";
import { file_game_messages } from "../game/messages_pb";
import type { GeneralPlayerMessage, GeneralServerMessage } from "../general/messages_pb";
import { file_general_messages } from "../general/messages_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file root/messages.proto.
 */
export const file_root_messages: GenFile = /*@__PURE__*/
  fileDesc("ChNyb290L21lc3NhZ2VzLnByb3RvEg1yb290X21lc3NhZ2VzItoBCg1QbGF5ZXJNZXNzYWdlEkEKD3ByZWdhbWVfbWVzc2FnZRgBIAEoCzImLnByZWdhbWVfbWVzc2FnZXMuUHJlZ2FtZVBsYXllck1lc3NhZ2VIABI4CgxnYW1lX21lc3NhZ2UYAiABKAsyIC5nYW1lX21lc3NhZ2VzLkdhbWVQbGF5ZXJNZXNzYWdlSAASQQoPZ2VuZXJhbF9tZXNzYWdlGAMgASgLMiYuZ2VuZXJhbF9tZXNzYWdlcy5HZW5lcmFsUGxheWVyTWVzc2FnZUgAQgkKB3BheWxvYWQi2gEKDVNlcnZlck1lc3NhZ2USQQoPZ2VuZXJhbF9tZXNzYWdlGAEgASgLMiYuZ2VuZXJhbF9tZXNzYWdlcy5HZW5lcmFsU2VydmVyTWVzc2FnZUgAEkEKD3ByZWdhbWVfbWVzc2FnZRgCIAEoCzImLnByZWdhbWVfbWVzc2FnZXMuUHJlZ2FtZVNlcnZlck1lc3NhZ2VIABI4CgxnYW1lX21lc3NhZ2UYAyABKAsyIC5nYW1lX21lc3NhZ2VzLkdhbWVTZXJ2ZXJNZXNzYWdlSABCCQoHcGF5bG9hZEJyChFjb20ucm9vdF9tZXNzYWdlc0INTWVzc2FnZXNQcm90b1ABogIDUlhYqgIMUm9vdE1lc3NhZ2VzygIMUm9vdE1lc3NhZ2Vz4gIYUm9vdE1lc3NhZ2VzXEdQQk1ldGFkYXRh6gIMUm9vdE1lc3NhZ2VzYgZwcm90bzM", [file_pregame_messages, file_game_messages, file_general_messages]);

/**
 * @generated from message root_messages.PlayerMessage
 */
export type PlayerMessage = Message<"root_messages.PlayerMessage"> & {
  /**
   * @generated from oneof root_messages.PlayerMessage.payload
   */
  payload: {
    /**
     * @generated from field: pregame_messages.PregamePlayerMessage pregame_message = 1;
     */
    value: PregamePlayerMessage;
    case: "pregameMessage";
  } | {
    /**
     * @generated from field: game_messages.GamePlayerMessage game_message = 2;
     */
    value: GamePlayerMessage;
    case: "gameMessage";
  } | {
    /**
     * @generated from field: general_messages.GeneralPlayerMessage general_message = 3;
     */
    value: GeneralPlayerMessage;
    case: "generalMessage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message root_messages.PlayerMessage.
 * Use `create(PlayerMessageSchema)` to create a new message.
 */
export const PlayerMessageSchema: GenMessage<PlayerMessage> = /*@__PURE__*/
  messageDesc(file_root_messages, 0);

/**
 * @generated from message root_messages.ServerMessage
 */
export type ServerMessage = Message<"root_messages.ServerMessage"> & {
  /**
   * @generated from oneof root_messages.ServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: general_messages.GeneralServerMessage general_message = 1;
     */
    value: GeneralServerMessage;
    case: "generalMessage";
  } | {
    /**
     * @generated from field: pregame_messages.PregameServerMessage pregame_message = 2;
     */
    value: PregameServerMessage;
    case: "pregameMessage";
  } | {
    /**
     * @generated from field: game_messages.GameServerMessage game_message = 3;
     */
    value: GameServerMessage;
    case: "gameMessage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message root_messages.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema: GenMessage<ServerMessage> = /*@__PURE__*/
  messageDesc(file_root_messages, 1);

