// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file root/model.proto (package root_models, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file root/model.proto.
 */
export const file_root_model: GenFile = /*@__PURE__*/
  fileDesc("ChByb290L21vZGVsLnByb3RvEgtyb290X21vZGVscyJpCgRTaGlwEg4KBmxlbmd0aBgBIAEoDRItCgtvcmllbnRhdGlvbhgCIAEoDjIYLnJvb3RfbW9kZWxzLk9yaWVudGF0aW9uEhAKCGhlYWRfcm93GAMgASgNEhAKCGhlYWRfY29sGAQgASgNKjwKC09yaWVudGF0aW9uEg8KC1VOU1BFQ0lGSUVEEAASDgoKSE9SSVpPTlRBTBABEgwKCFZFUlRJQ0FMEAJCZQoPY29tLnJvb3RfbW9kZWxzQgpNb2RlbFByb3RvUAGiAgNSWFiqAgpSb290TW9kZWxzygIKUm9vdE1vZGVsc+ICFlJvb3RNb2RlbHNcR1BCTWV0YWRhdGHqAgpSb290TW9kZWxzYgZwcm90bzM");

/**
 * @generated from message root_models.Ship
 */
export type Ship = Message<"root_models.Ship"> & {
  /**
   * @generated from field: uint32 length = 1;
   */
  length: number;

  /**
   * @generated from field: root_models.Orientation orientation = 2;
   */
  orientation: Orientation;

  /**
   * @generated from field: uint32 head_row = 3;
   */
  headRow: number;

  /**
   * @generated from field: uint32 head_col = 4;
   */
  headCol: number;
};

/**
 * Describes the message root_models.Ship.
 * Use `create(ShipSchema)` to create a new message.
 */
export const ShipSchema: GenMessage<Ship> = /*@__PURE__*/
  messageDesc(file_root_model, 0);

/**
 * @generated from enum root_models.Orientation
 */
export enum Orientation {
  /**
   * @generated from enum value: UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: HORIZONTAL = 1;
   */
  HORIZONTAL = 1,

  /**
   * @generated from enum value: VERTICAL = 2;
   */
  VERTICAL = 2,
}

/**
 * Describes the enum root_models.Orientation.
 */
export const OrientationSchema: GenEnum<Orientation> = /*@__PURE__*/
  enumDesc(file_root_model, 0);

