// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file general/messages.proto (package general_messages, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file general/messages.proto.
 */
export const file_general_messages: GenFile = /*@__PURE__*/
  fileDesc("ChZnZW5lcmFsL21lc3NhZ2VzLnByb3RvEhBnZW5lcmFsX21lc3NhZ2VzInsKFEdlbmVyYWxTZXJ2ZXJNZXNzYWdlElgKG29wcG9uZW50X2Nvbm5lY3Rpb25fbWVzc2FnZRgBIAEoCzIxLmdlbmVyYWxfbWVzc2FnZXMuU2VydmVyT3Bwb25lbnRDb25uZWN0aW9uTWVzc2FnZUgAQgkKB3BheWxvYWQiWgofU2VydmVyT3Bwb25lbnRDb25uZWN0aW9uTWVzc2FnZRIaChJvcHBvbmVudF9jb25uZWN0ZWQYASABKAgSGwoTaW5pdGlhbGx5X2Nvbm5lY3RlZBgCIAEoCCJ/ChRHZW5lcmFsUGxheWVyTWVzc2FnZRJcCh1vcHBvbmVudF9jb25uZWN0aW9uX2xpc3RlbmluZxgBIAEoCzIzLmdlbmVyYWxfbWVzc2FnZXMuUGxheWVyT3Bwb25lbnRDb25uZWN0aW9uTGlzdGVuaW5nSABCCQoHcGF5bG9hZCIjCiFQbGF5ZXJPcHBvbmVudENvbm5lY3Rpb25MaXN0ZW5pbmdCgQEKFGNvbS5nZW5lcmFsX21lc3NhZ2VzQg1NZXNzYWdlc1Byb3RvUAGiAgNHWFiqAg9HZW5lcmFsTWVzc2FnZXPKAg9HZW5lcmFsTWVzc2FnZXPiAhtHZW5lcmFsTWVzc2FnZXNcR1BCTWV0YWRhdGHqAg9HZW5lcmFsTWVzc2FnZXNiBnByb3RvMw");

/**
 * @generated from message general_messages.GeneralServerMessage
 */
export type GeneralServerMessage = Message<"general_messages.GeneralServerMessage"> & {
  /**
   * @generated from oneof general_messages.GeneralServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: general_messages.ServerOpponentConnectionMessage opponent_connection_message = 1;
     */
    value: ServerOpponentConnectionMessage;
    case: "opponentConnectionMessage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message general_messages.GeneralServerMessage.
 * Use `create(GeneralServerMessageSchema)` to create a new message.
 */
export const GeneralServerMessageSchema: GenMessage<GeneralServerMessage> = /*@__PURE__*/
  messageDesc(file_general_messages, 0);

/**
 * @generated from message general_messages.ServerOpponentConnectionMessage
 */
export type ServerOpponentConnectionMessage = Message<"general_messages.ServerOpponentConnectionMessage"> & {
  /**
   * @generated from field: bool opponent_connected = 1;
   */
  opponentConnected: boolean;

  /**
   * @generated from field: bool initially_connected = 2;
   */
  initiallyConnected: boolean;
};

/**
 * Describes the message general_messages.ServerOpponentConnectionMessage.
 * Use `create(ServerOpponentConnectionMessageSchema)` to create a new message.
 */
export const ServerOpponentConnectionMessageSchema: GenMessage<ServerOpponentConnectionMessage> = /*@__PURE__*/
  messageDesc(file_general_messages, 1);

/**
 * @generated from message general_messages.GeneralPlayerMessage
 */
export type GeneralPlayerMessage = Message<"general_messages.GeneralPlayerMessage"> & {
  /**
   * @generated from oneof general_messages.GeneralPlayerMessage.payload
   */
  payload: {
    /**
     * @generated from field: general_messages.PlayerOpponentConnectionRequest opponent_connection_listening = 1;
     */
    value: PlayerOpponentConnectionRequest;
    case: "opponentConnectionListening";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message general_messages.GeneralPlayerMessage.
 * Use `create(GeneralPlayerMessageSchema)` to create a new message.
 */
export const GeneralPlayerMessageSchema: GenMessage<GeneralPlayerMessage> = /*@__PURE__*/
  messageDesc(file_general_messages, 2);

/**
 * @generated from message general_messages.PlayerOpponentConnectionRequest
 */
export type PlayerOpponentConnectionRequest = Message<"general_messages.PlayerOpponentConnectionRequest"> & {
};

/**
 * Describes the message general_messages.PlayerOpponentConnectionRequest.
 * Use `create(PlayerOpponentConnectionRequestSchema)` to create a new message.
 */
export const PlayerOpponentConnectionRequestSchema: GenMessage<PlayerOpponentConnectionRequest> = /*@__PURE__*/
  messageDesc(file_general_messages, 3);

