// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file game/messages.proto (package game_messages, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ShipGridView } from "./model_pb";
import { file_game_model } from "./model_pb";
import type { Ship } from "../root/model_pb";
import { file_root_model } from "../root/model_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file game/messages.proto.
 */
export const file_game_messages: GenFile = /*@__PURE__*/
  fileDesc("ChNnYW1lL21lc3NhZ2VzLnByb3RvEg1nYW1lX21lc3NhZ2VzIlQKEUdhbWVQbGF5ZXJNZXNzYWdlEjQKBHNob3QYASABKAsyJC5nYW1lX21lc3NhZ2VzLkdhbWVQbGF5ZXJTaG90TWVzc2FnZUgAQgkKB3BheWxvYWQiLQoVR2FtZVBsYXllclNob3RNZXNzYWdlEgkKAXgYASABKAUSCQoBeRgCIAEoBSKeAQoRR2FtZVNlcnZlck1lc3NhZ2USOwoKZ2FtZV9zdGF0ZRgBIAEoCzIlLmdhbWVfbWVzc2FnZXMuR2FtZVNlcnZlclN0YXRlTWVzc2FnZUgAEkEKC3Nob3RfcmVzdWx0GAIgASgLMiouZ2FtZV9tZXNzYWdlcy5HYW1lU2VydmVyU2hvdFJlc3VsdE1lc3NhZ2VIAEIJCgdwYXlsb2FkIncKFkdhbWVTZXJ2ZXJTdGF0ZU1lc3NhZ2USKwoIb3duX2dyaWQYASABKAsyGS5nYW1lX21vZGVscy5TaGlwR3JpZFZpZXcSMAoNb3Bwb25lbnRfZ3JpZBgCIAEoCzIZLmdhbWVfbW9kZWxzLlNoaXBHcmlkVmlldyJpChtHYW1lU2VydmVyU2hvdFJlc3VsdE1lc3NhZ2USCQoBeBgBIAEoBRIJCgF5GAIgASgFEg4KBmlzX2hpdBgDIAEoCBIkCglzdW5rX3NoaXAYBCABKAsyES5yb290X21vZGVscy5TaGlwQnIKEWNvbS5nYW1lX21lc3NhZ2VzQg1NZXNzYWdlc1Byb3RvUAGiAgNHWFiqAgxHYW1lTWVzc2FnZXPKAgxHYW1lTWVzc2FnZXPiAhhHYW1lTWVzc2FnZXNcR1BCTWV0YWRhdGHqAgxHYW1lTWVzc2FnZXNiBnByb3RvMw", [file_game_model, file_root_model]);

/**
 * @generated from message game_messages.GamePlayerMessage
 */
export type GamePlayerMessage = Message<"game_messages.GamePlayerMessage"> & {
  /**
   * @generated from oneof game_messages.GamePlayerMessage.payload
   */
  payload: {
    /**
     * @generated from field: game_messages.GamePlayerShotMessage shot = 1;
     */
    value: GamePlayerShotMessage;
    case: "shot";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message game_messages.GamePlayerMessage.
 * Use `create(GamePlayerMessageSchema)` to create a new message.
 */
export const GamePlayerMessageSchema: GenMessage<GamePlayerMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 0);

/**
 * @generated from message game_messages.GamePlayerShotMessage
 */
export type GamePlayerShotMessage = Message<"game_messages.GamePlayerShotMessage"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * @generated from field: int32 y = 2;
   */
  y: number;
};

/**
 * Describes the message game_messages.GamePlayerShotMessage.
 * Use `create(GamePlayerShotMessageSchema)` to create a new message.
 */
export const GamePlayerShotMessageSchema: GenMessage<GamePlayerShotMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 1);

/**
 * @generated from message game_messages.GameServerMessage
 */
export type GameServerMessage = Message<"game_messages.GameServerMessage"> & {
  /**
   * @generated from oneof game_messages.GameServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: game_messages.GameServerStateMessage game_state = 1;
     */
    value: GameServerStateMessage;
    case: "gameState";
  } | {
    /**
     * @generated from field: game_messages.GameServerShotResultMessage shot_result = 2;
     */
    value: GameServerShotResultMessage;
    case: "shotResult";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message game_messages.GameServerMessage.
 * Use `create(GameServerMessageSchema)` to create a new message.
 */
export const GameServerMessageSchema: GenMessage<GameServerMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 2);

/**
 * @generated from message game_messages.GameServerStateMessage
 */
export type GameServerStateMessage = Message<"game_messages.GameServerStateMessage"> & {
  /**
   * @generated from field: game_models.ShipGridView own_grid = 1;
   */
  ownGrid?: ShipGridView;

  /**
   * @generated from field: game_models.ShipGridView opponent_grid = 2;
   */
  opponentGrid?: ShipGridView;
};

/**
 * Describes the message game_messages.GameServerStateMessage.
 * Use `create(GameServerStateMessageSchema)` to create a new message.
 */
export const GameServerStateMessageSchema: GenMessage<GameServerStateMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 3);

/**
 * @generated from message game_messages.GameServerShotResultMessage
 */
export type GameServerShotResultMessage = Message<"game_messages.GameServerShotResultMessage"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * @generated from field: int32 y = 2;
   */
  y: number;

  /**
   * @generated from field: bool is_hit = 3;
   */
  isHit: boolean;

  /**
   * @generated from field: root_models.Ship sunk_ship = 4;
   */
  sunkShip?: Ship;
};

/**
 * Describes the message game_messages.GameServerShotResultMessage.
 * Use `create(GameServerShotResultMessageSchema)` to create a new message.
 */
export const GameServerShotResultMessageSchema: GenMessage<GameServerShotResultMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 4);

