// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file game/model.proto (package game_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Orientation } from "../root/model_pb";
import { file_root_model } from "../root/model_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file game/model.proto.
 */
export const file_game_model: GenFile = /*@__PURE__*/
  fileDesc("ChBnYW1lL21vZGVsLnByb3RvEgtnYW1lX21vZGVscyJ5CgxTaGlwR3JpZFZpZXcSKwoEZ3JpZBgBIAMoCzIdLmdhbWVfbW9kZWxzLlNoaXBHcmlkVmlldy5Sb3cSJgoFc2hpcHMYAiADKAsyFy5nYW1lX21vZGVscy5BY3RpdmVTaGlwGhQKA1JvdxINCgVjZWxscxgBIAMoCCJ9CgpBY3RpdmVTaGlwEg4KBmxlbmd0aBgBIAEoBRItCgtvcmllbnRhdGlvbhgCIAEoDjIYLnJvb3RfbW9kZWxzLk9yaWVudGF0aW9uEhAKCGhlYWRfcm93GAMgASgFEhAKCGhlYWRfY29sGAQgASgFEgwKBGhpdHMYBSADKAhCZQoPY29tLmdhbWVfbW9kZWxzQgpNb2RlbFByb3RvUAGiAgNHWFiqAgpHYW1lTW9kZWxzygIKR2FtZU1vZGVsc+ICFkdhbWVNb2RlbHNcR1BCTWV0YWRhdGHqAgpHYW1lTW9kZWxzYgZwcm90bzM", [file_root_model]);

/**
 * @generated from message game_models.ShipGridView
 */
export type ShipGridView = Message<"game_models.ShipGridView"> & {
  /**
   * @generated from field: repeated game_models.ShipGridView.Row grid = 1;
   */
  grid: ShipGridView_Row[];

  /**
   * @generated from field: repeated game_models.ActiveShip ships = 2;
   */
  ships: ActiveShip[];
};

/**
 * Describes the message game_models.ShipGridView.
 * Use `create(ShipGridViewSchema)` to create a new message.
 */
export const ShipGridViewSchema: GenMessage<ShipGridView> = /*@__PURE__*/
  messageDesc(file_game_model, 0);

/**
 * @generated from message game_models.ShipGridView.Row
 */
export type ShipGridView_Row = Message<"game_models.ShipGridView.Row"> & {
  /**
   * @generated from field: repeated bool cells = 1;
   */
  cells: boolean[];
};

/**
 * Describes the message game_models.ShipGridView.Row.
 * Use `create(ShipGridView_RowSchema)` to create a new message.
 */
export const ShipGridView_RowSchema: GenMessage<ShipGridView_Row> = /*@__PURE__*/
  messageDesc(file_game_model, 0, 0);

/**
 * @generated from message game_models.ActiveShip
 */
export type ActiveShip = Message<"game_models.ActiveShip"> & {
  /**
   * @generated from field: int32 length = 1;
   */
  length: number;

  /**
   * @generated from field: root_models.Orientation orientation = 2;
   */
  orientation: Orientation;

  /**
   * @generated from field: int32 head_row = 3;
   */
  headRow: number;

  /**
   * @generated from field: int32 head_col = 4;
   */
  headCol: number;

  /**
   * @generated from field: repeated bool hits = 5;
   */
  hits: boolean[];
};

/**
 * Describes the message game_models.ActiveShip.
 * Use `create(ActiveShipSchema)` to create a new message.
 */
export const ActiveShipSchema: GenMessage<ActiveShip> = /*@__PURE__*/
  messageDesc(file_game_model, 1);

