// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file game/model.proto (package game_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Orientation } from "../root/model_pb";
import { file_root_model } from "../root/model_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file game/model.proto.
 */
export const file_game_model: GenFile = /*@__PURE__*/
  fileDesc("ChBnYW1lL21vZGVsLnByb3RvEgtnYW1lX21vZGVscyJ9CgxTaGlwR3JpZFZpZXcSLwoIaGl0X2dyaWQYASADKAsyHS5nYW1lX21vZGVscy5TaGlwR3JpZFZpZXcuUm93EiYKBXNoaXBzGAIgAygLMhcuZ2FtZV9tb2RlbHMuQWN0aXZlU2hpcBoUCgNSb3cSDQoFY2VsbHMYASADKAgifQoKQWN0aXZlU2hpcBIOCgZsZW5ndGgYASABKAUSLQoLb3JpZW50YXRpb24YAiABKA4yGC5yb290X21vZGVscy5PcmllbnRhdGlvbhIQCghoZWFkX3JvdxgDIAEoBRIQCghoZWFkX2NvbBgEIAEoBRIMCgRoaXRzGAUgAygIQmUKD2NvbS5nYW1lX21vZGVsc0IKTW9kZWxQcm90b1ABogIDR1hYqgIKR2FtZU1vZGVsc8oCCkdhbWVNb2RlbHPiAhZHYW1lTW9kZWxzXEdQQk1ldGFkYXRh6gIKR2FtZU1vZGVsc2IGcHJvdG8z", [file_root_model]);

/**
 * @generated from message game_models.ShipGridView
 */
export type ShipGridView = Message<"game_models.ShipGridView"> & {
  /**
   * @generated from field: repeated game_models.ShipGridView.Row hit_grid = 1;
   */
  hitGrid: ShipGridView_Row[];

  /**
   * @generated from field: repeated game_models.ActiveShip ships = 2;
   */
  ships: ActiveShip[];
};

/**
 * Describes the message game_models.ShipGridView.
 * Use `create(ShipGridViewSchema)` to create a new message.
 */
export const ShipGridViewSchema: GenMessage<ShipGridView> = /*@__PURE__*/
  messageDesc(file_game_model, 0);

/**
 * @generated from message game_models.ShipGridView.Row
 */
export type ShipGridView_Row = Message<"game_models.ShipGridView.Row"> & {
  /**
   * @generated from field: repeated bool cells = 1;
   */
  cells: boolean[];
};

/**
 * Describes the message game_models.ShipGridView.Row.
 * Use `create(ShipGridView_RowSchema)` to create a new message.
 */
export const ShipGridView_RowSchema: GenMessage<ShipGridView_Row> = /*@__PURE__*/
  messageDesc(file_game_model, 0, 0);

/**
 * @generated from message game_models.ActiveShip
 */
export type ActiveShip = Message<"game_models.ActiveShip"> & {
  /**
   * @generated from field: int32 length = 1;
   */
  length: number;

  /**
   * @generated from field: root_models.Orientation orientation = 2;
   */
  orientation: Orientation;

  /**
   * @generated from field: int32 head_row = 3;
   */
  headRow: number;

  /**
   * @generated from field: int32 head_col = 4;
   */
  headCol: number;

  /**
   * @generated from field: repeated bool hits = 5;
   */
  hits: boolean[];
};

/**
 * Describes the message game_models.ActiveShip.
 * Use `create(ActiveShipSchema)` to create a new message.
 */
export const ActiveShipSchema: GenMessage<ActiveShip> = /*@__PURE__*/
  messageDesc(file_game_model, 1);

