# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: game/messages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from . import game_models
from . import root_models


@dataclass
class GamePlayerMessage(betterproto.Message):
    shot: "GamePlayerShotMessage" = betterproto.message_field(1, group="payload")


@dataclass
class GamePlayerShotMessage(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)


@dataclass
class GameServerMessage(betterproto.Message):
    game_state: "GameServerStateMessage" = betterproto.message_field(1, group="payload")
    shot_result: "GameServerShotResultMessage" = betterproto.message_field(
        2, group="payload"
    )


@dataclass
class GameServerStateMessage(betterproto.Message):
    own_grid: game_models.ShipGridView = betterproto.message_field(1)
    opponent_grid: game_models.ShipGridView = betterproto.message_field(2)


@dataclass
class GameServerShotResultMessage(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)
    is_hit: bool = betterproto.bool_field(3)
    sunk_ship: root_models.Ship = betterproto.message_field(4)
