# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: game/model.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from . import root_models


@dataclass
class ShipGridView(betterproto.Message):
    grid: List["ShipGridViewRow"] = betterproto.message_field(1)
    ships: List["ActiveShip"] = betterproto.message_field(2)


@dataclass
class ShipGridViewRow(betterproto.Message):
    cells: List[bool] = betterproto.bool_field(1)


@dataclass
class ActiveShip(betterproto.Message):
    length: int = betterproto.int32_field(1)
    orientation: root_models.Orientation = betterproto.enum_field(2)
    head_row: int = betterproto.int32_field(3)
    head_col: int = betterproto.int32_field(4)
    hits: List[bool] = betterproto.bool_field(5)
