# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: general/messages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GeneralServerMessage(betterproto.Message):
    opponent_connection_message: "ServerOpponentConnectionMessage" = (
        betterproto.message_field(1, group="payload")
    )


@dataclass
class ServerOpponentConnectionMessage(betterproto.Message):
    opponent_connected: bool = betterproto.bool_field(1)
    initially_connected: bool = betterproto.bool_field(2)


@dataclass
class GeneralPlayerMessage(betterproto.Message):
    opponent_connection_listening: "PlayerOpponentConnectionPoll" = (
        betterproto.message_field(1, group="payload")
    )


@dataclass
class PlayerOpponentConnectionPoll(betterproto.Message):
    pass
