# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: pregame/messages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from . import root_models


@dataclass
class PregameServerMessage(betterproto.Message):
    ready_state: "PregameServerReadyStateMessage" = betterproto.message_field(
        1, group="payload"
    )


@dataclass
class PregameServerReadyStateMessage(betterproto.Message):
    num_ready_players: int = betterproto.int32_field(1)
    self_ready: bool = betterproto.bool_field(2)


@dataclass
class PregamePlayerMessage(betterproto.Message):
    set_ready_state: "PregamePlayerSetReadyStateMessage" = betterproto.message_field(
        1, group="payload"
    )


@dataclass
class PregamePlayerSetReadyStateMessage(betterproto.Message):
    ships: List[root_models.Ship] = betterproto.message_field(1)
