# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: root/messages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from . import game_messages
from . import general_messages
from . import pregame_messages


@dataclass
class PlayerMessage(betterproto.Message):
    general_message: general_messages.GeneralPlayerMessage = betterproto.message_field(
        1, group="payload"
    )
    pregame_message: pregame_messages.PregamePlayerMessage = betterproto.message_field(
        2, group="payload"
    )
    game_message: game_messages.GamePlayerMessage = betterproto.message_field(
        3, group="payload"
    )


@dataclass
class ServerMessage(betterproto.Message):
    general_message: general_messages.GeneralServerMessage = betterproto.message_field(
        1, group="payload"
    )
    pregame_message: pregame_messages.PregameServerMessage = betterproto.message_field(
        2, group="payload"
    )
    game_message: game_messages.GameServerMessage = betterproto.message_field(
        3, group="payload"
    )
