# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: root/model.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Orientation(betterproto.Enum):
    UNSPECIFIED = 0
    HORIZONTAL = 1
    VERTICAL = 2


@dataclass
class Ship(betterproto.Message):
    length: int = betterproto.int32_field(1)
    orientation: "Orientation" = betterproto.enum_field(2)
    head_row: int = betterproto.int32_field(3)
    head_col: int = betterproto.int32_field(4)
