# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: pregame/messages.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

import betterproto
from pydantic import model_validator
from pydantic.dataclasses import rebuild_dataclass

from .. import root_models as _root_models__


@dataclass(eq=False, repr=False)
class PregameServerMessage(betterproto.Message):
    ready_state: "PregameServerReadyStateMessage | None" = betterproto.message_field(
        1, optional=True, group="payload"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False)
class PregameServerReadyStateMessage(betterproto.Message):
    num_ready_players: int = betterproto.uint32_field(1)
    self_ready: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class PregamePlayerMessage(betterproto.Message):
    set_ready_state: "PregamePlayerSetReadyStateMessage | None" = (
        betterproto.message_field(1, optional=True, group="payload")
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False)
class PregamePlayerSetReadyStateMessage(betterproto.Message):
    ships: "list[_root_models__.Ship]" = betterproto.message_field(1)


rebuild_dataclass(PregameServerMessage)  # type: ignore
rebuild_dataclass(PregamePlayerMessage)  # type: ignore
rebuild_dataclass(PregamePlayerSetReadyStateMessage)  # type: ignore
