/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PregameWSServerStateMessage } from './PregameWSServerStateMessage';
import {
    PregameWSServerStateMessageFromJSON,
    PregameWSServerStateMessageFromJSONTyped,
    PregameWSServerStateMessageToJSON,
    PregameWSServerStateMessageToJSONTyped,
} from './PregameWSServerStateMessage';
import type { PregameWSPlayerReadyMessage } from './PregameWSPlayerReadyMessage';
import {
    PregameWSPlayerReadyMessageFromJSON,
    PregameWSPlayerReadyMessageFromJSONTyped,
    PregameWSPlayerReadyMessageToJSON,
    PregameWSPlayerReadyMessageToJSONTyped,
} from './PregameWSPlayerReadyMessage';
import type { WSServerOpponentConnectionMessage } from './WSServerOpponentConnectionMessage';
import {
    WSServerOpponentConnectionMessageFromJSON,
    WSServerOpponentConnectionMessageFromJSONTyped,
    WSServerOpponentConnectionMessageToJSON,
    WSServerOpponentConnectionMessageToJSONTyped,
} from './WSServerOpponentConnectionMessage';
import type { GameWSServerStateMessage } from './GameWSServerStateMessage';
import {
    GameWSServerStateMessageFromJSON,
    GameWSServerStateMessageFromJSONTyped,
    GameWSServerStateMessageToJSON,
    GameWSServerStateMessageToJSONTyped,
} from './GameWSServerStateMessage';
import type { Ship } from './Ship';
import {
    ShipFromJSON,
    ShipFromJSONTyped,
    ShipToJSON,
    ShipToJSONTyped,
} from './Ship';
import type { GameWSGamePlayerShotMessageMessage } from './GameWSGamePlayerShotMessageMessage';
import {
    GameWSGamePlayerShotMessageMessageFromJSON,
    GameWSGamePlayerShotMessageMessageFromJSONTyped,
    GameWSGamePlayerShotMessageMessageToJSON,
    GameWSGamePlayerShotMessageMessageToJSONTyped,
} from './GameWSGamePlayerShotMessageMessage';
import type { GameWSGameServerShotResultMessageMessage } from './GameWSGameServerShotResultMessageMessage';
import {
    GameWSGameServerShotResultMessageMessageFromJSON,
    GameWSGameServerShotResultMessageMessageFromJSONTyped,
    GameWSGameServerShotResultMessageMessageToJSON,
    GameWSGameServerShotResultMessageMessageToJSONTyped,
} from './GameWSGameServerShotResultMessageMessage';
import type { View } from './View';
import {
    ViewFromJSON,
    ViewFromJSONTyped,
    ViewToJSON,
    ViewToJSONTyped,
} from './View';

/**
 * 
 * @export
 * @interface Data
 */
export interface Data {
    /**
     * 
     * @type {boolean}
     * @memberof Data
     */
    opponentConnected: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Data
     */
    initiallyConnected: boolean;
    /**
     * 
     * @type {number}
     * @memberof Data
     */
    numPlayersReady: number;
    /**
     * 
     * @type {boolean}
     * @memberof Data
     */
    selfReady: boolean;
    /**
     * 
     * @type {number}
     * @memberof Data
     */
    row: number;
    /**
     * 
     * @type {number}
     * @memberof Data
     */
    col: number;
    /**
     * 
     * @type {View}
     * @memberof Data
     */
    ownShipGrid: View;
    /**
     * 
     * @type {View}
     * @memberof Data
     */
    opponentShipGrid: View;
    /**
     * 
     * @type {boolean}
     * @memberof Data
     */
    hit: boolean;
    /**
     * 
     * @type {Ship}
     * @memberof Data
     */
    sunkShip: Ship;
    /**
     * 
     * @type {Array<Ship>}
     * @memberof Data
     */
    ships: Array<Ship>;
}

/**
 * Check if a given object implements the Data interface.
 */
export function instanceOfData(value: object): value is Data {
    if (!('opponentConnected' in value) || value['opponentConnected'] === undefined) return false;
    if (!('initiallyConnected' in value) || value['initiallyConnected'] === undefined) return false;
    if (!('numPlayersReady' in value) || value['numPlayersReady'] === undefined) return false;
    if (!('selfReady' in value) || value['selfReady'] === undefined) return false;
    if (!('row' in value) || value['row'] === undefined) return false;
    if (!('col' in value) || value['col'] === undefined) return false;
    if (!('ownShipGrid' in value) || value['ownShipGrid'] === undefined) return false;
    if (!('opponentShipGrid' in value) || value['opponentShipGrid'] === undefined) return false;
    if (!('hit' in value) || value['hit'] === undefined) return false;
    if (!('sunkShip' in value) || value['sunkShip'] === undefined) return false;
    if (!('ships' in value) || value['ships'] === undefined) return false;
    return true;
}

export function DataFromJSON(json: any): Data {
    return DataFromJSONTyped(json, false);
}

export function DataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Data {
    if (json == null) {
        return json;
    }
    return {
        
        'opponentConnected': json['opponentConnected'],
        'initiallyConnected': json['initiallyConnected'],
        'numPlayersReady': json['numPlayersReady'],
        'selfReady': json['selfReady'],
        'row': json['row'],
        'col': json['col'],
        'ownShipGrid': ViewFromJSON(json['ownShipGrid']),
        'opponentShipGrid': ViewFromJSON(json['opponentShipGrid']),
        'hit': json['hit'],
        'sunkShip': ShipFromJSON(json['sunkShip']),
        'ships': ((json['ships'] as Array<any>).map(ShipFromJSON)),
    };
}

export function DataToJSON(json: any): Data {
    return DataToJSONTyped(json, false);
}

export function DataToJSONTyped(value?: Data | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opponentConnected': value['opponentConnected'],
        'initiallyConnected': value['initiallyConnected'],
        'numPlayersReady': value['numPlayersReady'],
        'selfReady': value['selfReady'],
        'row': value['row'],
        'col': value['col'],
        'ownShipGrid': ViewToJSON(value['ownShipGrid']),
        'opponentShipGrid': ViewToJSON(value['opponentShipGrid']),
        'hit': value['hit'],
        'sunkShip': ShipToJSON(value['sunkShip']),
        'ships': ((value['ships'] as Array<any>).map(ShipToJSON)),
    };
}

