/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ship } from './Ship';
import {
    ShipFromJSON,
    ShipFromJSONTyped,
    ShipToJSON,
    ShipToJSONTyped,
} from './Ship';

/**
 * 
 * @export
 * @interface GameWSServerShotResultMessage
 */
export interface GameWSServerShotResultMessage {
    /**
     * 
     * @type {number}
     * @memberof GameWSServerShotResultMessage
     */
    row: number;
    /**
     * 
     * @type {number}
     * @memberof GameWSServerShotResultMessage
     */
    col: number;
    /**
     * 
     * @type {boolean}
     * @memberof GameWSServerShotResultMessage
     */
    hit: boolean;
    /**
     * 
     * @type {Ship}
     * @memberof GameWSServerShotResultMessage
     */
    sunkShip: Ship | null;
}

/**
 * Check if a given object implements the GameWSServerShotResultMessage interface.
 */
export function instanceOfGameWSServerShotResultMessage(value: object): value is GameWSServerShotResultMessage {
    if (!('row' in value) || value['row'] === undefined) return false;
    if (!('col' in value) || value['col'] === undefined) return false;
    if (!('hit' in value) || value['hit'] === undefined) return false;
    if (!('sunkShip' in value) || value['sunkShip'] === undefined) return false;
    return true;
}

export function GameWSServerShotResultMessageFromJSON(json: any): GameWSServerShotResultMessage {
    return GameWSServerShotResultMessageFromJSONTyped(json, false);
}

export function GameWSServerShotResultMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameWSServerShotResultMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'row': json['row'],
        'col': json['col'],
        'hit': json['hit'],
        'sunkShip': ShipFromJSON(json['sunkShip']),
    };
}

export function GameWSServerShotResultMessageToJSON(json: any): GameWSServerShotResultMessage {
    return GameWSServerShotResultMessageToJSONTyped(json, false);
}

export function GameWSServerShotResultMessageToJSONTyped(value?: GameWSServerShotResultMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row': value['row'],
        'col': value['col'],
        'hit': value['hit'],
        'sunkShip': ShipToJSON(value['sunkShip']),
    };
}

