/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ship } from './Ship';
import {
    ShipFromJSON,
    ShipFromJSONTyped,
    ShipToJSON,
    ShipToJSONTyped,
} from './Ship';

/**
 * 
 * @export
 * @interface GameWSGameServerShotResultMessageMessage
 */
export interface GameWSGameServerShotResultMessageMessage {
    /**
     * 
     * @type {number}
     * @memberof GameWSGameServerShotResultMessageMessage
     */
    row: number;
    /**
     * 
     * @type {number}
     * @memberof GameWSGameServerShotResultMessageMessage
     */
    col: number;
    /**
     * 
     * @type {boolean}
     * @memberof GameWSGameServerShotResultMessageMessage
     */
    hit: boolean;
    /**
     * 
     * @type {Ship}
     * @memberof GameWSGameServerShotResultMessageMessage
     */
    sunkShip: Ship | null;
}

/**
 * Check if a given object implements the GameWSGameServerShotResultMessageMessage interface.
 */
export function instanceOfGameWSGameServerShotResultMessageMessage(value: object): value is GameWSGameServerShotResultMessageMessage {
    if (!('row' in value) || value['row'] === undefined) return false;
    if (!('col' in value) || value['col'] === undefined) return false;
    if (!('hit' in value) || value['hit'] === undefined) return false;
    if (!('sunkShip' in value) || value['sunkShip'] === undefined) return false;
    return true;
}

export function GameWSGameServerShotResultMessageMessageFromJSON(json: any): GameWSGameServerShotResultMessageMessage {
    return GameWSGameServerShotResultMessageMessageFromJSONTyped(json, false);
}

export function GameWSGameServerShotResultMessageMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameWSGameServerShotResultMessageMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'row': json['row'],
        'col': json['col'],
        'hit': json['hit'],
        'sunkShip': ShipFromJSON(json['sunkShip']),
    };
}

export function GameWSGameServerShotResultMessageMessageToJSON(json: any): GameWSGameServerShotResultMessageMessage {
    return GameWSGameServerShotResultMessageMessageToJSONTyped(json, false);
}

export function GameWSGameServerShotResultMessageMessageToJSONTyped(value?: GameWSGameServerShotResultMessageMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row': value['row'],
        'col': value['col'],
        'hit': value['hit'],
        'sunkShip': ShipToJSON(value['sunkShip']),
    };
}

