/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameWSGamePlayerShotMessageMessage
 */
export interface GameWSGamePlayerShotMessageMessage {
    /**
     * 
     * @type {number}
     * @memberof GameWSGamePlayerShotMessageMessage
     */
    row: number;
    /**
     * 
     * @type {number}
     * @memberof GameWSGamePlayerShotMessageMessage
     */
    col: number;
}

/**
 * Check if a given object implements the GameWSGamePlayerShotMessageMessage interface.
 */
export function instanceOfGameWSGamePlayerShotMessageMessage(value: object): value is GameWSGamePlayerShotMessageMessage {
    if (!('row' in value) || value['row'] === undefined) return false;
    if (!('col' in value) || value['col'] === undefined) return false;
    return true;
}

export function GameWSGamePlayerShotMessageMessageFromJSON(json: any): GameWSGamePlayerShotMessageMessage {
    return GameWSGamePlayerShotMessageMessageFromJSONTyped(json, false);
}

export function GameWSGamePlayerShotMessageMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameWSGamePlayerShotMessageMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'row': json['row'],
        'col': json['col'],
    };
}

export function GameWSGamePlayerShotMessageMessageToJSON(json: any): GameWSGamePlayerShotMessageMessage {
    return GameWSGamePlayerShotMessageMessageToJSONTyped(json, false);
}

export function GameWSGamePlayerShotMessageMessageToJSONTyped(value?: GameWSGamePlayerShotMessageMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row': value['row'],
        'col': value['col'],
    };
}

