/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Orientation = {
    Horizontal: 'horizontal',
    Vertical: 'vertical'
} as const;
export type Orientation = typeof Orientation[keyof typeof Orientation];


export function instanceOfOrientation(value: any): boolean {
    for (const key in Orientation) {
        if (Object.prototype.hasOwnProperty.call(Orientation, key)) {
            if (Orientation[key as keyof typeof Orientation] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OrientationFromJSON(json: any): Orientation {
    return OrientationFromJSONTyped(json, false);
}

export function OrientationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Orientation {
    return json as Orientation;
}

export function OrientationToJSON(value?: Orientation | null): any {
    return value as any;
}

export function OrientationToJSONTyped(value: any, ignoreDiscriminator: boolean): Orientation {
    return value as Orientation;
}

