/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Orientation } from './Orientation';
import {
    OrientationFromJSON,
    OrientationFromJSONTyped,
    OrientationToJSON,
    OrientationToJSONTyped,
} from './Orientation';

/**
 * 
 * @export
 * @interface Ship
 */
export interface Ship {
    /**
     * 
     * @type {number}
     * @memberof Ship
     */
    length?: number;
    /**
     * 
     * @type {Orientation}
     * @memberof Ship
     */
    orientation?: Orientation;
    /**
     * 
     * @type {number}
     * @memberof Ship
     */
    headRow?: number;
    /**
     * 
     * @type {number}
     * @memberof Ship
     */
    headCol?: number;
}



/**
 * Check if a given object implements the Ship interface.
 */
export function instanceOfShip(value: object): value is Ship {
    return true;
}

export function ShipFromJSON(json: any): Ship {
    return ShipFromJSONTyped(json, false);
}

export function ShipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ship {
    if (json == null) {
        return json;
    }
    return {
        
        'length': json['length'] == null ? undefined : json['length'],
        'orientation': json['orientation'] == null ? undefined : OrientationFromJSON(json['orientation']),
        'headRow': json['headRow'] == null ? undefined : json['headRow'],
        'headCol': json['headCol'] == null ? undefined : json['headCol'],
    };
}

export function ShipToJSON(json: any): Ship {
    return ShipToJSONTyped(json, false);
}

export function ShipToJSONTyped(value?: Ship | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'length': value['length'],
        'orientation': OrientationToJSON(value['orientation']),
        'headRow': value['headRow'],
        'headCol': value['headCol'],
    };
}

