/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WSServerOpponentConnectionMessage
 */
export interface WSServerOpponentConnectionMessage {
    /**
     * 
     * @type {boolean}
     * @memberof WSServerOpponentConnectionMessage
     */
    opponentConnected: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WSServerOpponentConnectionMessage
     */
    initiallyConnected: boolean;
}

/**
 * Check if a given object implements the WSServerOpponentConnectionMessage interface.
 */
export function instanceOfWSServerOpponentConnectionMessage(value: object): value is WSServerOpponentConnectionMessage {
    if (!('opponentConnected' in value) || value['opponentConnected'] === undefined) return false;
    if (!('initiallyConnected' in value) || value['initiallyConnected'] === undefined) return false;
    return true;
}

export function WSServerOpponentConnectionMessageFromJSON(json: any): WSServerOpponentConnectionMessage {
    return WSServerOpponentConnectionMessageFromJSONTyped(json, false);
}

export function WSServerOpponentConnectionMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WSServerOpponentConnectionMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'opponentConnected': json['opponentConnected'],
        'initiallyConnected': json['initiallyConnected'],
    };
}

export function WSServerOpponentConnectionMessageToJSON(json: any): WSServerOpponentConnectionMessage {
    return WSServerOpponentConnectionMessageToJSONTyped(json, false);
}

export function WSServerOpponentConnectionMessageToJSONTyped(value?: WSServerOpponentConnectionMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opponentConnected': value['opponentConnected'],
        'initiallyConnected': value['initiallyConnected'],
    };
}

