# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: root/model.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

import betterproto
from pydantic.dataclasses import rebuild_dataclass


class Orientation(betterproto.Enum):
    UNSPECIFIED = 0
    HORIZONTAL = 1
    VERTICAL = 2

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False)
class Ship(betterproto.Message):
    length: int = betterproto.uint32_field(1)
    orientation: "Orientation" = betterproto.enum_field(2)
    head_row: int = betterproto.uint32_field(3)
    head_col: int = betterproto.uint32_field(4)


rebuild_dataclass(Ship)  # type: ignore
