/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ship } from './Ship';
import {
    ShipFromJSON,
    ShipFromJSONTyped,
    ShipToJSON,
    ShipToJSONTyped,
} from './Ship';

/**
 * 
 * @export
 * @interface GameParams
 */
export interface GameParams {
    /**
     * 
     * @type {number}
     * @memberof GameParams
     */
    battleGridRows: number;
    /**
     * 
     * @type {number}
     * @memberof GameParams
     */
    battleGridCols: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GameParams
     */
    shipLengths: { [key: string]: number; };
    /**
     * 
     * @type {Array<Ship>}
     * @memberof GameParams
     */
    ownShips: Array<Ship>;
}

/**
 * Check if a given object implements the GameParams interface.
 */
export function instanceOfGameParams(value: object): value is GameParams {
    if (!('battleGridRows' in value) || value['battleGridRows'] === undefined) return false;
    if (!('battleGridCols' in value) || value['battleGridCols'] === undefined) return false;
    if (!('shipLengths' in value) || value['shipLengths'] === undefined) return false;
    if (!('ownShips' in value) || value['ownShips'] === undefined) return false;
    return true;
}

export function GameParamsFromJSON(json: any): GameParams {
    return GameParamsFromJSONTyped(json, false);
}

export function GameParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameParams {
    if (json == null) {
        return json;
    }
    return {
        
        'battleGridRows': json['battleGridRows'],
        'battleGridCols': json['battleGridCols'],
        'shipLengths': json['shipLengths'],
        'ownShips': ((json['ownShips'] as Array<any>).map(ShipFromJSON)),
    };
}

export function GameParamsToJSON(json: any): GameParams {
    return GameParamsToJSONTyped(json, false);
}

export function GameParamsToJSONTyped(value?: GameParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'battleGridRows': value['battleGridRows'],
        'battleGridCols': value['battleGridCols'],
        'shipLengths': value['shipLengths'],
        'ownShips': ((value['ownShips'] as Array<any>).map(ShipToJSON)),
    };
}

