/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GameMode = {
    Singleshot: 'SINGLESHOT',
    Salvo: 'SALVO',
    Streak: 'STREAK'
} as const;
export type GameMode = typeof GameMode[keyof typeof GameMode];


export function instanceOfGameMode(value: any): boolean {
    for (const key in GameMode) {
        if (Object.prototype.hasOwnProperty.call(GameMode, key)) {
            if (GameMode[key as keyof typeof GameMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GameModeFromJSON(json: any): GameMode {
    return GameModeFromJSONTyped(json, false);
}

export function GameModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameMode {
    return json as GameMode;
}

export function GameModeToJSON(value?: GameMode | null): any {
    return value as any;
}

export function GameModeToJSONTyped(value: any, ignoreDiscriminator: boolean): GameMode {
    return value as GameMode;
}

