/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GameParams,
  HTTPValidationError,
} from '../models/index';
import {
    GameParamsFromJSON,
    GameParamsToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateGameGamesCreatePostRequest {
    playerId: string;
    gameParams: GameParams;
}

export interface CreatePlayerPlayersCreatePostRequest {
    playerId?: string | null;
}

export interface GetPregameParamsGamesGameIdParamsGetRequest {
    gameId: string;
    playerId: string;
}

export interface JoinGameGamesGameIdJoinPostRequest {
    gameId: string;
    playerId: string;
}

export interface WelcomeFullPathGetRequest {
    fullPath: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Create Game
     */
    async createGameGamesCreatePostRaw(requestParameters: CreateGameGamesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['playerId'] == null) {
            throw new runtime.RequiredError(
                'playerId',
                'Required parameter "playerId" was null or undefined when calling createGameGamesCreatePost().'
            );
        }

        if (requestParameters['gameParams'] == null) {
            throw new runtime.RequiredError(
                'gameParams',
                'Required parameter "gameParams" was null or undefined when calling createGameGamesCreatePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['playerId'] != null) {
            queryParameters['playerId'] = requestParameters['playerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/games/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GameParamsToJSON(requestParameters['gameParams']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Game
     */
    async createGameGamesCreatePost(requestParameters: CreateGameGamesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createGameGamesCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Player
     */
    async createPlayerPlayersCreatePostRaw(requestParameters: CreatePlayerPlayersCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['playerId'] != null) {
            queryParameters['playerId'] = requestParameters['playerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/players/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Player
     */
    async createPlayerPlayersCreatePost(requestParameters: CreatePlayerPlayersCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createPlayerPlayersCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Pregame Params
     */
    async getPregameParamsGamesGameIdParamsGetRaw(requestParameters: GetPregameParamsGamesGameIdParamsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameParams>> {
        if (requestParameters['gameId'] == null) {
            throw new runtime.RequiredError(
                'gameId',
                'Required parameter "gameId" was null or undefined when calling getPregameParamsGamesGameIdParamsGet().'
            );
        }

        if (requestParameters['playerId'] == null) {
            throw new runtime.RequiredError(
                'playerId',
                'Required parameter "playerId" was null or undefined when calling getPregameParamsGamesGameIdParamsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['playerId'] != null) {
            queryParameters['playerId'] = requestParameters['playerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/games/{gameId}/params`;
        urlPath = urlPath.replace(`{${"gameId"}}`, encodeURIComponent(String(requestParameters['gameId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameParamsFromJSON(jsonValue));
    }

    /**
     * Get Pregame Params
     */
    async getPregameParamsGamesGameIdParamsGet(requestParameters: GetPregameParamsGamesGameIdParamsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameParams> {
        const response = await this.getPregameParamsGamesGameIdParamsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Join Game
     */
    async joinGameGamesGameIdJoinPostRaw(requestParameters: JoinGameGamesGameIdJoinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['gameId'] == null) {
            throw new runtime.RequiredError(
                'gameId',
                'Required parameter "gameId" was null or undefined when calling joinGameGamesGameIdJoinPost().'
            );
        }

        if (requestParameters['playerId'] == null) {
            throw new runtime.RequiredError(
                'playerId',
                'Required parameter "playerId" was null or undefined when calling joinGameGamesGameIdJoinPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['playerId'] != null) {
            queryParameters['playerId'] = requestParameters['playerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/games/{gameId}/join`;
        urlPath = urlPath.replace(`{${"gameId"}}`, encodeURIComponent(String(requestParameters['gameId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Join Game
     */
    async joinGameGamesGameIdJoinPost(requestParameters: JoinGameGamesGameIdJoinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.joinGameGamesGameIdJoinPostRaw(requestParameters, initOverrides);
    }

    /**
     * Welcome
     */
    async welcomeFullPathGetRaw(requestParameters: WelcomeFullPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['fullPath'] == null) {
            throw new runtime.RequiredError(
                'fullPath',
                'Required parameter "fullPath" was null or undefined when calling welcomeFullPathGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/{full_path}`;
        urlPath = urlPath.replace(`{${"full_path"}}`, encodeURIComponent(String(requestParameters['fullPath'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Welcome
     */
    async welcomeFullPathGet(requestParameters: WelcomeFullPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.welcomeFullPathGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
