# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: root/messages.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

import betterproto
from pydantic import model_validator
from pydantic.dataclasses import rebuild_dataclass

from .. import (
    game_messages as _game_messages__,
    general_messages as _general_messages__,
    pregame_messages as _pregame_messages__,
)


@dataclass(eq=False, repr=False)
class PlayerMessage(betterproto.Message):
    pregame_message: "_pregame_messages__.PregamePlayerMessage | None" = (
        betterproto.message_field(1, optional=True, group="payload")
    )
    game_message: "_game_messages__.GamePlayerMessage | None" = (
        betterproto.message_field(2, optional=True, group="payload")
    )
    general_message: "_general_messages__.GeneralPlayerMessage | None" = (
        betterproto.message_field(3, optional=True, group="payload")
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False)
class ServerMessage(betterproto.Message):
    general_message: "_general_messages__.GeneralServerMessage | None" = (
        betterproto.message_field(1, optional=True, group="payload")
    )
    pregame_message: "_pregame_messages__.PregameServerMessage | None" = (
        betterproto.message_field(2, optional=True, group="payload")
    )
    game_message: "_game_messages__.GameServerMessage | None" = (
        betterproto.message_field(3, optional=True, group="payload")
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


rebuild_dataclass(PlayerMessage)  # type: ignore
rebuild_dataclass(ServerMessage)  # type: ignore
