# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: game/messages.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

import betterproto
from pydantic import model_validator
from pydantic.dataclasses import rebuild_dataclass

from .. import game_models as _game_models__


class GameOverResult(betterproto.Enum):
    UNKNOWN = 0
    WIN = 1
    LOSS = 2
    PREMATURE = 3

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False)
class GamePlayerMessage(betterproto.Message):
    shot: "GamePlayerShotMessage | None" = betterproto.message_field(
        1, optional=True, group="payload"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False)
class GamePlayerShotMessage(betterproto.Message):
    row: int = betterproto.uint32_field(1)
    column: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class GameServerMessage(betterproto.Message):
    game_state: "GameServerStateMessage | None" = betterproto.message_field(
        1, optional=True, group="payload"
    )
    shot_result: "GameServerShotResultMessage | None" = betterproto.message_field(
        2, optional=True, group="payload"
    )
    shot: "GameServerShotMessage | None" = betterproto.message_field(
        3, optional=True, group="payload"
    )
    turn: "GameServerTurnMessage | None" = betterproto.message_field(
        4, optional=True, group="payload"
    )
    game_over: "GameServerGameOverMessage | None" = betterproto.message_field(
        5, optional=True, group="payload"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False)
class GameServerStateMessage(betterproto.Message):
    own_grid: "_game_models__.ShipGridView" = betterproto.message_field(1)
    opponent_grid: "_game_models__.ShipGridView" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class GameServerShotResultMessage(betterproto.Message):
    shot: "GameServerShotMessage" = betterproto.message_field(1)
    is_hit: bool = betterproto.bool_field(3)
    sunk_ship: "_game_models__.ActiveShip | None" = betterproto.message_field(
        4, optional=True
    )


@dataclass(eq=False, repr=False)
class GameServerShotMessage(betterproto.Message):
    row: int = betterproto.uint32_field(1)
    column: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class GameServerTurnMessage(betterproto.Message):
    opponents_turn: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class GameServerGameOverMessage(betterproto.Message):
    result: "GameOverResult" = betterproto.enum_field(1)


rebuild_dataclass(GamePlayerMessage)  # type: ignore
rebuild_dataclass(GameServerMessage)  # type: ignore
rebuild_dataclass(GameServerStateMessage)  # type: ignore
rebuild_dataclass(GameServerShotResultMessage)  # type: ignore
rebuild_dataclass(GameServerGameOverMessage)  # type: ignore
