// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file general/messages.proto (package general_messages, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file general/messages.proto.
 */
export const file_general_messages: GenFile = /*@__PURE__*/
  fileDesc("ChZnZW5lcmFsL21lc3NhZ2VzLnByb3RvEhBnZW5lcmFsX21lc3NhZ2VzIsIBChRHZW5lcmFsU2VydmVyTWVzc2FnZRJYChtvcHBvbmVudF9jb25uZWN0aW9uX21lc3NhZ2UYASABKAsyMS5nZW5lcmFsX21lc3NhZ2VzLlNlcnZlck9wcG9uZW50Q29ubmVjdGlvbk1lc3NhZ2VIABJFChFoZWFydGJlYXRfcmVxdWVzdBgCIAEoCzIoLmdlbmVyYWxfbWVzc2FnZXMuU2VydmVySGVhcnRiZWF0UmVxdWVzdEgAQgkKB3BheWxvYWQiWgofU2VydmVyT3Bwb25lbnRDb25uZWN0aW9uTWVzc2FnZRIaChJvcHBvbmVudF9jb25uZWN0ZWQYASABKAgSGwoTaW5pdGlhbGx5X2Nvbm5lY3RlZBgCIAEoCCIYChZTZXJ2ZXJIZWFydGJlYXRSZXF1ZXN0ImoKFEdlbmVyYWxQbGF5ZXJNZXNzYWdlEkcKEmhlYXJ0YmVhdF9yZXNwb25zZRgBIAEoCzIpLmdlbmVyYWxfbWVzc2FnZXMuUGxheWVySGVhcnRiZWF0UmVzcG9uc2VIAEIJCgdwYXlsb2FkIhkKF1BsYXllckhlYXJ0YmVhdFJlc3BvbnNlQoEBChRjb20uZ2VuZXJhbF9tZXNzYWdlc0INTWVzc2FnZXNQcm90b1ABogIDR1hYqgIPR2VuZXJhbE1lc3NhZ2VzygIPR2VuZXJhbE1lc3NhZ2Vz4gIbR2VuZXJhbE1lc3NhZ2VzXEdQQk1ldGFkYXRh6gIPR2VuZXJhbE1lc3NhZ2VzYgZwcm90bzM");

/**
 * @generated from message general_messages.GeneralServerMessage
 */
export type GeneralServerMessage = Message<"general_messages.GeneralServerMessage"> & {
  /**
   * @generated from oneof general_messages.GeneralServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: general_messages.ServerOpponentConnectionMessage opponent_connection_message = 1;
     */
    value: ServerOpponentConnectionMessage;
    case: "opponentConnectionMessage";
  } | {
    /**
     * @generated from field: general_messages.ServerHeartbeatRequest heartbeat_request = 2;
     */
    value: ServerHeartbeatRequest;
    case: "heartbeatRequest";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message general_messages.GeneralServerMessage.
 * Use `create(GeneralServerMessageSchema)` to create a new message.
 */
export const GeneralServerMessageSchema: GenMessage<GeneralServerMessage> = /*@__PURE__*/
  messageDesc(file_general_messages, 0);

/**
 * @generated from message general_messages.ServerOpponentConnectionMessage
 */
export type ServerOpponentConnectionMessage = Message<"general_messages.ServerOpponentConnectionMessage"> & {
  /**
   * @generated from field: bool opponent_connected = 1;
   */
  opponentConnected: boolean;

  /**
   * @generated from field: bool initially_connected = 2;
   */
  initiallyConnected: boolean;
};

/**
 * Describes the message general_messages.ServerOpponentConnectionMessage.
 * Use `create(ServerOpponentConnectionMessageSchema)` to create a new message.
 */
export const ServerOpponentConnectionMessageSchema: GenMessage<ServerOpponentConnectionMessage> = /*@__PURE__*/
  messageDesc(file_general_messages, 1);

/**
 * @generated from message general_messages.ServerHeartbeatRequest
 */
export type ServerHeartbeatRequest = Message<"general_messages.ServerHeartbeatRequest"> & {
};

/**
 * Describes the message general_messages.ServerHeartbeatRequest.
 * Use `create(ServerHeartbeatRequestSchema)` to create a new message.
 */
export const ServerHeartbeatRequestSchema: GenMessage<ServerHeartbeatRequest> = /*@__PURE__*/
  messageDesc(file_general_messages, 2);

/**
 * @generated from message general_messages.GeneralPlayerMessage
 */
export type GeneralPlayerMessage = Message<"general_messages.GeneralPlayerMessage"> & {
  /**
   * @generated from oneof general_messages.GeneralPlayerMessage.payload
   */
  payload: {
    /**
     * @generated from field: general_messages.PlayerHeartbeatResponse heartbeat_response = 1;
     */
    value: PlayerHeartbeatResponse;
    case: "heartbeatResponse";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message general_messages.GeneralPlayerMessage.
 * Use `create(GeneralPlayerMessageSchema)` to create a new message.
 */
export const GeneralPlayerMessageSchema: GenMessage<GeneralPlayerMessage> = /*@__PURE__*/
  messageDesc(file_general_messages, 3);

/**
 * @generated from message general_messages.PlayerHeartbeatResponse
 */
export type PlayerHeartbeatResponse = Message<"general_messages.PlayerHeartbeatResponse"> & {
};

/**
 * Describes the message general_messages.PlayerHeartbeatResponse.
 * Use `create(PlayerHeartbeatResponseSchema)` to create a new message.
 */
export const PlayerHeartbeatResponseSchema: GenMessage<PlayerHeartbeatResponse> = /*@__PURE__*/
  messageDesc(file_general_messages, 4);

