# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: general/messages.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

import betterproto
from pydantic import model_validator
from pydantic.dataclasses import rebuild_dataclass


@dataclass(eq=False, repr=False)
class GeneralServerMessage(betterproto.Message):
    opponent_connection_message: "ServerOpponentConnectionMessage | None" = (
        betterproto.message_field(1, optional=True, group="payload")
    )
    heartbeat_request: "ServerHeartbeatRequest | None" = betterproto.message_field(
        2, optional=True, group="payload"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False)
class ServerOpponentConnectionMessage(betterproto.Message):
    opponent_connected: bool = betterproto.bool_field(1)
    initially_connected: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class ServerHeartbeatRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GeneralPlayerMessage(betterproto.Message):
    heartbeat_response: "PlayerHeartbeatResponse | None" = betterproto.message_field(
        1, optional=True, group="payload"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False)
class PlayerHeartbeatResponse(betterproto.Message):
    pass


rebuild_dataclass(GeneralServerMessage)  # type: ignore
rebuild_dataclass(GeneralPlayerMessage)  # type: ignore
