// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file game/messages.proto (package game_messages, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ActiveShip, ShipGridView } from "./model_pb";
import { file_game_model } from "./model_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file game/messages.proto.
 */
export const file_game_messages: GenFile = /*@__PURE__*/
  fileDesc("ChNnYW1lL21lc3NhZ2VzLnByb3RvEg1nYW1lX21lc3NhZ2VzIlQKEUdhbWVQbGF5ZXJNZXNzYWdlEjQKBHNob3QYASABKAsyJC5nYW1lX21lc3NhZ2VzLkdhbWVQbGF5ZXJTaG90TWVzc2FnZUgAQgkKB3BheWxvYWQiNAoVR2FtZVBsYXllclNob3RNZXNzYWdlEgsKA3JvdxgBIAEoBRIOCgZjb2x1bW4YAiABKAUiyQIKEUdhbWVTZXJ2ZXJNZXNzYWdlEjsKCmdhbWVfc3RhdGUYASABKAsyJS5nYW1lX21lc3NhZ2VzLkdhbWVTZXJ2ZXJTdGF0ZU1lc3NhZ2VIABJBCgtzaG90X3Jlc3VsdBgCIAEoCzIqLmdhbWVfbWVzc2FnZXMuR2FtZVNlcnZlclNob3RSZXN1bHRNZXNzYWdlSAASNAoEc2hvdBgDIAEoCzIkLmdhbWVfbWVzc2FnZXMuR2FtZVNlcnZlclNob3RNZXNzYWdlSAASNAoEdHVybhgEIAEoCzIkLmdhbWVfbWVzc2FnZXMuR2FtZVNlcnZlclR1cm5NZXNzYWdlSAASPQoJZ2FtZV9vdmVyGAUgASgLMiguZ2FtZV9tZXNzYWdlcy5HYW1lU2VydmVyR2FtZU92ZXJNZXNzYWdlSABCCQoHcGF5bG9hZCJ3ChZHYW1lU2VydmVyU3RhdGVNZXNzYWdlEisKCG93bl9ncmlkGAEgASgLMhkuZ2FtZV9tb2RlbHMuU2hpcEdyaWRWaWV3EjAKDW9wcG9uZW50X2dyaWQYAiABKAsyGS5nYW1lX21vZGVscy5TaGlwR3JpZFZpZXcioAEKG0dhbWVTZXJ2ZXJTaG90UmVzdWx0TWVzc2FnZRIyCgRzaG90GAEgASgLMiQuZ2FtZV9tZXNzYWdlcy5HYW1lU2VydmVyU2hvdE1lc3NhZ2USDgoGaXNfaGl0GAMgASgIEi8KCXN1bmtfc2hpcBgEIAEoCzIXLmdhbWVfbW9kZWxzLkFjdGl2ZVNoaXBIAIgBAUIMCgpfc3Vua19zaGlwIjQKFUdhbWVTZXJ2ZXJTaG90TWVzc2FnZRILCgNyb3cYASABKAUSDgoGY29sdW1uGAIgASgFIhcKFUdhbWVTZXJ2ZXJUdXJuTWVzc2FnZSJKChlHYW1lU2VydmVyR2FtZU92ZXJNZXNzYWdlEi0KBnJlc3VsdBgBIAEoDjIdLmdhbWVfbWVzc2FnZXMuR2FtZU92ZXJSZXN1bHQqMgoOR2FtZU92ZXJSZXN1bHQSBwoDV0lOEAASCAoETE9TUxABEg0KCVBSRU1BVFVSRRACQnIKEWNvbS5nYW1lX21lc3NhZ2VzQg1NZXNzYWdlc1Byb3RvUAGiAgNHWFiqAgxHYW1lTWVzc2FnZXPKAgxHYW1lTWVzc2FnZXPiAhhHYW1lTWVzc2FnZXNcR1BCTWV0YWRhdGHqAgxHYW1lTWVzc2FnZXNiBnByb3RvMw", [file_game_model]);

/**
 * @generated from message game_messages.GamePlayerMessage
 */
export type GamePlayerMessage = Message<"game_messages.GamePlayerMessage"> & {
  /**
   * @generated from oneof game_messages.GamePlayerMessage.payload
   */
  payload: {
    /**
     * @generated from field: game_messages.GamePlayerShotMessage shot = 1;
     */
    value: GamePlayerShotMessage;
    case: "shot";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message game_messages.GamePlayerMessage.
 * Use `create(GamePlayerMessageSchema)` to create a new message.
 */
export const GamePlayerMessageSchema: GenMessage<GamePlayerMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 0);

/**
 * @generated from message game_messages.GamePlayerShotMessage
 */
export type GamePlayerShotMessage = Message<"game_messages.GamePlayerShotMessage"> & {
  /**
   * @generated from field: int32 row = 1;
   */
  row: number;

  /**
   * @generated from field: int32 column = 2;
   */
  column: number;
};

/**
 * Describes the message game_messages.GamePlayerShotMessage.
 * Use `create(GamePlayerShotMessageSchema)` to create a new message.
 */
export const GamePlayerShotMessageSchema: GenMessage<GamePlayerShotMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 1);

/**
 * @generated from message game_messages.GameServerMessage
 */
export type GameServerMessage = Message<"game_messages.GameServerMessage"> & {
  /**
   * @generated from oneof game_messages.GameServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: game_messages.GameServerStateMessage game_state = 1;
     */
    value: GameServerStateMessage;
    case: "gameState";
  } | {
    /**
     * @generated from field: game_messages.GameServerShotResultMessage shot_result = 2;
     */
    value: GameServerShotResultMessage;
    case: "shotResult";
  } | {
    /**
     * @generated from field: game_messages.GameServerShotMessage shot = 3;
     */
    value: GameServerShotMessage;
    case: "shot";
  } | {
    /**
     * @generated from field: game_messages.GameServerTurnMessage turn = 4;
     */
    value: GameServerTurnMessage;
    case: "turn";
  } | {
    /**
     * @generated from field: game_messages.GameServerGameOverMessage game_over = 5;
     */
    value: GameServerGameOverMessage;
    case: "gameOver";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message game_messages.GameServerMessage.
 * Use `create(GameServerMessageSchema)` to create a new message.
 */
export const GameServerMessageSchema: GenMessage<GameServerMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 2);

/**
 * @generated from message game_messages.GameServerStateMessage
 */
export type GameServerStateMessage = Message<"game_messages.GameServerStateMessage"> & {
  /**
   * @generated from field: game_models.ShipGridView own_grid = 1;
   */
  ownGrid?: ShipGridView;

  /**
   * @generated from field: game_models.ShipGridView opponent_grid = 2;
   */
  opponentGrid?: ShipGridView;
};

/**
 * Describes the message game_messages.GameServerStateMessage.
 * Use `create(GameServerStateMessageSchema)` to create a new message.
 */
export const GameServerStateMessageSchema: GenMessage<GameServerStateMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 3);

/**
 * @generated from message game_messages.GameServerShotResultMessage
 */
export type GameServerShotResultMessage = Message<"game_messages.GameServerShotResultMessage"> & {
  /**
   * @generated from field: game_messages.GameServerShotMessage shot = 1;
   */
  shot?: GameServerShotMessage;

  /**
   * @generated from field: bool is_hit = 3;
   */
  isHit: boolean;

  /**
   * @generated from field: optional game_models.ActiveShip sunk_ship = 4;
   */
  sunkShip?: ActiveShip;
};

/**
 * Describes the message game_messages.GameServerShotResultMessage.
 * Use `create(GameServerShotResultMessageSchema)` to create a new message.
 */
export const GameServerShotResultMessageSchema: GenMessage<GameServerShotResultMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 4);

/**
 * @generated from message game_messages.GameServerShotMessage
 */
export type GameServerShotMessage = Message<"game_messages.GameServerShotMessage"> & {
  /**
   * @generated from field: int32 row = 1;
   */
  row: number;

  /**
   * @generated from field: int32 column = 2;
   */
  column: number;
};

/**
 * Describes the message game_messages.GameServerShotMessage.
 * Use `create(GameServerShotMessageSchema)` to create a new message.
 */
export const GameServerShotMessageSchema: GenMessage<GameServerShotMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 5);

/**
 * @generated from message game_messages.GameServerTurnMessage
 */
export type GameServerTurnMessage = Message<"game_messages.GameServerTurnMessage"> & {
};

/**
 * Describes the message game_messages.GameServerTurnMessage.
 * Use `create(GameServerTurnMessageSchema)` to create a new message.
 */
export const GameServerTurnMessageSchema: GenMessage<GameServerTurnMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 6);

/**
 * @generated from message game_messages.GameServerGameOverMessage
 */
export type GameServerGameOverMessage = Message<"game_messages.GameServerGameOverMessage"> & {
  /**
   * @generated from field: game_messages.GameOverResult result = 1;
   */
  result: GameOverResult;
};

/**
 * Describes the message game_messages.GameServerGameOverMessage.
 * Use `create(GameServerGameOverMessageSchema)` to create a new message.
 */
export const GameServerGameOverMessageSchema: GenMessage<GameServerGameOverMessage> = /*@__PURE__*/
  messageDesc(file_game_messages, 7);

/**
 * @generated from enum game_messages.GameOverResult
 */
export enum GameOverResult {
  /**
   * @generated from enum value: WIN = 0;
   */
  WIN = 0,

  /**
   * @generated from enum value: LOSS = 1;
   */
  LOSS = 1,

  /**
   * @generated from enum value: PREMATURE = 2;
   */
  PREMATURE = 2,
}

/**
 * Describes the enum game_messages.GameOverResult.
 */
export const GameOverResultSchema: GenEnum<GameOverResult> = /*@__PURE__*/
  enumDesc(file_game_messages, 0);

