// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file game/model.proto (package game_models, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Orientation } from "../root/model_pb";
import { file_root_model } from "../root/model_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file game/model.proto.
 */
export const file_game_model: GenFile = /*@__PURE__*/
  fileDesc("ChBnYW1lL21vZGVsLnByb3RvEgtnYW1lX21vZGVscyLsAQoMU2hpcEdyaWRWaWV3Ei8KCGhpdF9ncmlkGAEgAygLMh0uZ2FtZV9tb2RlbHMuU2hpcEdyaWRWaWV3LlJvdxImCgVzaGlwcxgCIAMoCzIXLmdhbWVfbW9kZWxzLkFjdGl2ZVNoaXAaOAoDUm93EjEKBWNlbGxzGAEgAygOMiIuZ2FtZV9tb2RlbHMuU2hpcEdyaWRWaWV3LkhpdFN0YXRlIkkKCEhpdFN0YXRlEgsKB1VOS05PV04QABINCglVTlRPVUNIRUQQARIICgRNSVNTEAISBwoDSElUEAMSDgoKSU1QT1NTSUJMRRAEIn0KCkFjdGl2ZVNoaXASDgoGbGVuZ3RoGAEgASgFEi0KC29yaWVudGF0aW9uGAIgASgOMhgucm9vdF9tb2RlbHMuT3JpZW50YXRpb24SEAoIaGVhZF9yb3cYAyABKAUSEAoIaGVhZF9jb2wYBCABKAUSDAoEaGl0cxgFIAMoCEJlCg9jb20uZ2FtZV9tb2RlbHNCCk1vZGVsUHJvdG9QAaICA0dYWKoCCkdhbWVNb2RlbHPKAgpHYW1lTW9kZWxz4gIWR2FtZU1vZGVsc1xHUEJNZXRhZGF0YeoCCkdhbWVNb2RlbHNiBnByb3RvMw", [file_root_model]);

/**
 * @generated from message game_models.ShipGridView
 */
export type ShipGridView = Message<"game_models.ShipGridView"> & {
  /**
   * @generated from field: repeated game_models.ShipGridView.Row hit_grid = 1;
   */
  hitGrid: ShipGridView_Row[];

  /**
   * @generated from field: repeated game_models.ActiveShip ships = 2;
   */
  ships: ActiveShip[];
};

/**
 * Describes the message game_models.ShipGridView.
 * Use `create(ShipGridViewSchema)` to create a new message.
 */
export const ShipGridViewSchema: GenMessage<ShipGridView> = /*@__PURE__*/
  messageDesc(file_game_model, 0);

/**
 * @generated from message game_models.ShipGridView.Row
 */
export type ShipGridView_Row = Message<"game_models.ShipGridView.Row"> & {
  /**
   * @generated from field: repeated game_models.ShipGridView.HitState cells = 1;
   */
  cells: ShipGridView_HitState[];
};

/**
 * Describes the message game_models.ShipGridView.Row.
 * Use `create(ShipGridView_RowSchema)` to create a new message.
 */
export const ShipGridView_RowSchema: GenMessage<ShipGridView_Row> = /*@__PURE__*/
  messageDesc(file_game_model, 0, 0);

/**
 * @generated from enum game_models.ShipGridView.HitState
 */
export enum ShipGridView_HitState {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: UNTOUCHED = 1;
   */
  UNTOUCHED = 1,

  /**
   * @generated from enum value: MISS = 2;
   */
  MISS = 2,

  /**
   * @generated from enum value: HIT = 3;
   */
  HIT = 3,

  /**
   * @generated from enum value: IMPOSSIBLE = 4;
   */
  IMPOSSIBLE = 4,
}

/**
 * Describes the enum game_models.ShipGridView.HitState.
 */
export const ShipGridView_HitStateSchema: GenEnum<ShipGridView_HitState> = /*@__PURE__*/
  enumDesc(file_game_model, 0, 0);

/**
 * @generated from message game_models.ActiveShip
 */
export type ActiveShip = Message<"game_models.ActiveShip"> & {
  /**
   * @generated from field: int32 length = 1;
   */
  length: number;

  /**
   * @generated from field: root_models.Orientation orientation = 2;
   */
  orientation: Orientation;

  /**
   * @generated from field: int32 head_row = 3;
   */
  headRow: number;

  /**
   * @generated from field: int32 head_col = 4;
   */
  headCol: number;

  /**
   * @generated from field: repeated bool hits = 5;
   */
  hits: boolean[];
};

/**
 * Describes the message game_models.ActiveShip.
 * Use `create(ActiveShipSchema)` to create a new message.
 */
export const ActiveShipSchema: GenMessage<ActiveShip> = /*@__PURE__*/
  messageDesc(file_game_model, 1);

