// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file pregame/messages.proto (package pregame_messages, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Ship } from "../root/model_pb";
import { file_root_model } from "../root/model_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file pregame/messages.proto.
 */
export const file_pregame_messages: GenFile = /*@__PURE__*/
  fileDesc("ChZwcmVnYW1lL21lc3NhZ2VzLnByb3RvEhBwcmVnYW1lX21lc3NhZ2VzImoKFFByZWdhbWVTZXJ2ZXJNZXNzYWdlEkcKC3JlYWR5X3N0YXRlGAEgASgLMjAucHJlZ2FtZV9tZXNzYWdlcy5QcmVnYW1lU2VydmVyUmVhZHlTdGF0ZU1lc3NhZ2VIAEIJCgdwYXlsb2FkIk8KHlByZWdhbWVTZXJ2ZXJSZWFkeVN0YXRlTWVzc2FnZRIZChFudW1fcmVhZHlfcGxheWVycxgBIAEoDRISCgpzZWxmX3JlYWR5GAIgASgIInEKFFByZWdhbWVQbGF5ZXJNZXNzYWdlEk4KD3NldF9yZWFkeV9zdGF0ZRgBIAEoCzIzLnByZWdhbWVfbWVzc2FnZXMuUHJlZ2FtZVBsYXllclNldFJlYWR5U3RhdGVNZXNzYWdlSABCCQoHcGF5bG9hZCJFCiFQcmVnYW1lUGxheWVyU2V0UmVhZHlTdGF0ZU1lc3NhZ2USIAoFc2hpcHMYASADKAsyES5yb290X21vZGVscy5TaGlwQoEBChRjb20ucHJlZ2FtZV9tZXNzYWdlc0INTWVzc2FnZXNQcm90b1ABogIDUFhYqgIPUHJlZ2FtZU1lc3NhZ2VzygIPUHJlZ2FtZU1lc3NhZ2Vz4gIbUHJlZ2FtZU1lc3NhZ2VzXEdQQk1ldGFkYXRh6gIPUHJlZ2FtZU1lc3NhZ2VzYgZwcm90bzM", [file_root_model]);

/**
 * @generated from message pregame_messages.PregameServerMessage
 */
export type PregameServerMessage = Message<"pregame_messages.PregameServerMessage"> & {
  /**
   * @generated from oneof pregame_messages.PregameServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: pregame_messages.PregameServerReadyStateMessage ready_state = 1;
     */
    value: PregameServerReadyStateMessage;
    case: "readyState";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message pregame_messages.PregameServerMessage.
 * Use `create(PregameServerMessageSchema)` to create a new message.
 */
export const PregameServerMessageSchema: GenMessage<PregameServerMessage> = /*@__PURE__*/
  messageDesc(file_pregame_messages, 0);

/**
 * @generated from message pregame_messages.PregameServerReadyStateMessage
 */
export type PregameServerReadyStateMessage = Message<"pregame_messages.PregameServerReadyStateMessage"> & {
  /**
   * @generated from field: uint32 num_ready_players = 1;
   */
  numReadyPlayers: number;

  /**
   * @generated from field: bool self_ready = 2;
   */
  selfReady: boolean;
};

/**
 * Describes the message pregame_messages.PregameServerReadyStateMessage.
 * Use `create(PregameServerReadyStateMessageSchema)` to create a new message.
 */
export const PregameServerReadyStateMessageSchema: GenMessage<PregameServerReadyStateMessage> = /*@__PURE__*/
  messageDesc(file_pregame_messages, 1);

/**
 * @generated from message pregame_messages.PregamePlayerMessage
 */
export type PregamePlayerMessage = Message<"pregame_messages.PregamePlayerMessage"> & {
  /**
   * @generated from oneof pregame_messages.PregamePlayerMessage.payload
   */
  payload: {
    /**
     * @generated from field: pregame_messages.PregamePlayerSetReadyStateMessage set_ready_state = 1;
     */
    value: PregamePlayerSetReadyStateMessage;
    case: "setReadyState";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message pregame_messages.PregamePlayerMessage.
 * Use `create(PregamePlayerMessageSchema)` to create a new message.
 */
export const PregamePlayerMessageSchema: GenMessage<PregamePlayerMessage> = /*@__PURE__*/
  messageDesc(file_pregame_messages, 2);

/**
 * @generated from message pregame_messages.PregamePlayerSetReadyStateMessage
 */
export type PregamePlayerSetReadyStateMessage = Message<"pregame_messages.PregamePlayerSetReadyStateMessage"> & {
  /**
   * @generated from field: repeated root_models.Ship ships = 1;
   */
  ships: Ship[];
};

/**
 * Describes the message pregame_messages.PregamePlayerSetReadyStateMessage.
 * Use `create(PregamePlayerSetReadyStateMessageSchema)` to create a new message.
 */
export const PregamePlayerSetReadyStateMessageSchema: GenMessage<PregamePlayerSetReadyStateMessage> = /*@__PURE__*/
  messageDesc(file_pregame_messages, 3);

